// Nieuwe bol-content per Shopify-handle, NL en FR.
// Bron van elke claim: Shopify (beschrijving, specs-/custom-metafields, Amazon-metafields) plus
// visuele controle van de productfoto's (Finn = leer + canvas, Beau = gevlochten hengsels, goudkleurig beslag).
// Niet opgenomen omdat de bronnen elkaar tegenspreken: literinhoud Milo en Lorne, afmetingen Cleo,
// laptopvak Lilith, binnenvoering (katoen vs. polyester), meegeleverde dustbag.
//
// Elke entry: colours (Shopify-variantnaam -> NL/FR kleurnaam), nl/fr title(v) en desc(v).
// v = { nl, fr, size } (size alleen voor de riem).

const NL_LEER = `<h3>Plantaardig gelooid leer dat mooier wordt</h3><p>Beocca maakt tassen en accessoires van 100% plantaardig gelooid volnerf leer. Dit leer wordt zonder chroom gelooid en ontwikkelt met gebruik een eigen patina: de kleur wordt warmer en kleine gebruikssporen worden onderdeel van het karakter. Elk exemplaar wordt met de hand gemaakt door ervaren ambachtslieden, is ontworpen in Nederland en heeft 2 jaar fabrieksgarantie.</p>`;
const FR_CUIR = `<h3>Un cuir à tannage végétal qui embellit avec le temps</h3><p>Beocca fabrique ses sacs et accessoires en cuir pleine fleur 100 % à tannage végétal. Ce cuir est tanné sans chrome et développe à l'usage une patine unique : la couleur se réchauffe et les traces d'utilisation font partie de son caractère. Chaque pièce est faite main par des artisans expérimentés, conçue aux Pays-Bas et couverte par une garantie fabricant de 2 ans.</p>`;

module.exports = {
  'rugzak-cleo': {
    model: 'Cleo',
    colours: { 'Glad zwart': { nl: 'Zwart', fr: 'Noir', nlMat: 'glad leer', frMat: 'cuir lisse', suede: false },
               'Suede Zwart': { nl: 'Suède Zwart', fr: 'Daim Noir', nlMat: 'suède', frMat: 'daim', suede: true } },
    nl: {
      title: v => `Beocca Cleo ${v.suede ? 'Suède' : 'Leren'} Rugzak Dames Heren - Laptoptas 14 inch - Compacte Laptop Rugtas - Plantaardig Gelooid Leer - 20 liter - ${v.nl}`,
      desc: v => `<p><strong>Beocca Cleo, compacte leren rugzak met 14 inch laptopvak.</strong> Compact, maar groots in mogelijkheden. De Cleo is een stijlvolle rugzak voor wie een wat kleiner formaat prefereert zonder in te leveren op functionaliteit. Met ruimte voor een 14 inch laptop of iPad en je dagelijkse essentials is hij de ideale metgezel voor werk, studie of een dag in de stad. Het compacte formaat maakt hem ook geschikt als handbagage.</p><p>Het gevoerde laptopvak beschermt je laptop, de praktische binnenvakken houden oplader, kabels en kleine spullen georganiseerd. De verstelbare schouderbanden en de lichtgewicht constructie zorgen voor draagcomfort de hele dag door. Deze uitvoering is gemaakt van ${v.nlMat} in de kleur ${v.nl.toLowerCase()}.</p><h3>Kenmerken van de Beocca Cleo rugzak</h3><ul><li>Gevoerd laptopvak voor laptops tot 14 inch of een iPad</li><li>Inhoud 20 liter, geschikt als handbagage</li><li>Praktische binnenvakken voor oplader en kleine spullen</li><li>Verstelbare schouderbanden</li><li>Lichtgewicht constructie</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>De Cleo is een leren rugzak voor dames en heren die van collegezaal naar vergaderruimte naar weekend gaat. Verkrijgbaar in glad zwart leer en suède zwart.</p>`,
    },
    fr: {
      title: v => `Beocca Cleo Sac à Dos en ${v.suede ? 'Daim' : 'Cuir'} Femme Homme - Sac Ordinateur 14 Pouces - Sac à Dos Compact - Cuir à Tannage Végétal - 20 litres - ${v.fr}`,
      desc: v => `<p><strong>Beocca Cleo, sac à dos en cuir compact avec compartiment ordinateur 14 pouces.</strong> Compact, mais généreux en possibilités. Le Cleo est un sac à dos élégant pour celles et ceux qui préfèrent un format plus petit sans renoncer à la fonctionnalité. Avec de la place pour un ordinateur portable 14 pouces ou un iPad et vos essentiels du quotidien, il vous accompagne au travail, à l'université ou pour une journée en ville. Son format compact en fait aussi un bagage à main pratique.</p><p>Le compartiment matelassé protège votre ordinateur, les poches intérieures gardent chargeur, câbles et petits objets bien rangés. Les bretelles réglables et la construction légère assurent un confort de port toute la journée. Cette version est réalisée en ${v.frMat}, coloris ${v.fr.toLowerCase()}.</p><h3>Caractéristiques du sac à dos Beocca Cleo</h3><ul><li>Compartiment matelassé pour ordinateur portable jusqu'à 14 pouces ou iPad</li><li>Volume de 20 litres, format bagage à main</li><li>Poches intérieures pratiques pour chargeur et petits objets</li><li>Bretelles réglables</li><li>Construction légère</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Le Cleo est un sac à dos en cuir pour femme et homme qui passe de l'amphithéâtre à la salle de réunion et au week-end. Disponible en cuir lisse noir et en daim noir.</p>`,
    },
  },

  'rugzak-mavis': {
    model: 'Mavis',
    colours: { 'Cognac': { nl: 'Cognac', fr: 'Cognac' }, 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Groen': { nl: 'Groen', fr: 'Vert' } },
    nl: {
      title: v => `Beocca Mavis Leren Rugzak Dames Heren - Laptoptas 15,6 inch - Laptop Rugtas met Gevoerd Laptopvak - Plantaardig Gelooid Leer - 23 liter - ${v.nl}`,
      desc: v => `<p><strong>Beocca Mavis, stoere leren rugzak voor 15,6 inch laptops.</strong> Mavis is stoer, minimalistisch en gemaakt voor mensen die dagelijks een laptop meenemen maar geen concessies willen doen aan stijl of kwaliteit. Met ruimte voor een 15,6 inch laptop en al je dagelijkse benodigdheden is hij groot genoeg voor alles wat je nodig hebt, maar niet zo groot dat hij onhandig wordt.</p><p>Het dikke plantaardig gelooide leer is slijtvast en behoudt zijn vorm, ook na maanden vol beladen te zijn gedragen. Het gevoerde laptopvak beschermt je laptop tegen stoten en krassen, de extra binnenvakken houden oplader, kabels en kleine spullen georganiseerd. Verstevigde naden, een stevige bodem en hoogwaardige hardware maken de Mavis geschikt voor dagelijks intensief gebruik.</p><h3>Kenmerken van de Beocca Mavis rugzak</h3><ul><li>Gevoerd laptopvak voor laptops tot 15,6 inch</li><li>Afmetingen 35 x 45 x 10 cm, inhoud 23 liter</li><li>Meerdere binnenvakken voor organisatie</li><li>Verstelbare, gevoerde schouderbanden</li><li>Verstevigde bodem en naden, sluiting met rits en magneet</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Op kantoor past de Mavis bij een professionele look, op de universiteit is hij een betrouwbare studiegenoot en in het weekend gaat hij mee op stedentrip. Verkrijgbaar in cognac, zwart en groen. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Mavis Sac à Dos en Cuir Femme Homme - Sac Ordinateur 15,6 Pouces - Compartiment Matelassé - Cuir à Tannage Végétal - 23 litres - ${v.fr}`,
      desc: v => `<p><strong>Beocca Mavis, sac à dos en cuir robuste pour ordinateur 15,6 pouces.</strong> Le Mavis est robuste, minimaliste et conçu pour celles et ceux qui transportent un ordinateur portable au quotidien sans faire de compromis sur le style ou la qualité. Avec de la place pour un ordinateur 15,6 pouces et tous vos essentiels, il est assez grand pour tout ce dont vous avez besoin, sans jamais devenir encombrant.</p><p>Le cuir épais à tannage végétal résiste à l'usure et garde sa forme, même après des mois de port bien chargé. Le compartiment matelassé protège votre ordinateur des chocs et des rayures, les poches intérieures gardent chargeur, câbles et petits objets bien rangés. Coutures renforcées, fond solide et quincaillerie de qualité font du Mavis un sac à dos pensé pour un usage intensif quotidien.</p><h3>Caractéristiques du sac à dos Beocca Mavis</h3><ul><li>Compartiment matelassé pour ordinateur portable jusqu'à 15,6 pouces</li><li>Dimensions 35 x 45 x 10 cm, volume de 23 litres</li><li>Plusieurs poches intérieures pour l'organisation</li><li>Bretelles réglables et rembourrées</li><li>Fond et coutures renforcés, fermeture à glissière et aimant</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Au bureau, le Mavis accompagne une tenue professionnelle, à l'université c'est un compagnon d'études fiable et le week-end il part en city trip. Disponible en cognac, noir et vert. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'rugzak-lorne-cognac': {
    model: 'Lorne',
    colours: { 'Cognac': { nl: 'Cognac', fr: 'Cognac' } },
    nl: {
      title: v => `Beocca Lorne Leren Rugzak Dames Klein - Compacte Rugtas met Gevoerd Laptopvak - Plantaardig Gelooid Leer - 26 x 30 x 8 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Lorne, veelzijdige leren rugzak voor dagelijks gebruik.</strong> De Lorne combineert comfort met stijl en past overal bij: van kantoor tot weekend, van stad tot natuur. Hij is compact genoeg om de hele dag licht te dragen en biedt toch ruimte aan alles wat je dagelijks bij je hebt.</p><p>Binnenin vind je een gevoerd laptopvak, een ruim hoofdvak en binnenvakken voor accessoires. Het voorvak houdt kleine spullen binnen handbereik. De gevoerde, verstelbare schouderbanden snijden niet en dragen comfortabel, ook bij een volle tas. De warme cognac kleur van het plantaardig gelooide leer ontwikkelt met gebruik een prachtige patina.</p><h3>Kenmerken van de Beocca Lorne rugzak</h3><ul><li>Compacte rugtas van 26 x 30 x 8 cm</li><li>Gevoerd laptopvak</li><li>Ruim hoofdvak met binnenvakken voor accessoires</li><li>Voorvak voor kleine spullen</li><li>Verstelbare, gevoerde schouderbanden</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Zoek je een kleine leren rugzak voor dames die bij elke gelegenheid past, van zakelijke meetings tot casual uitjes? De Lorne in cognac is een tijdloze keuze.</p>`,
    },
    fr: {
      title: v => `Beocca Lorne Sac à Dos en Cuir Femme - Petit Sac à Dos Compact avec Compartiment Ordinateur Matelassé - Cuir à Tannage Végétal - 26 x 30 x 8 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Lorne, sac à dos en cuir polyvalent pour tous les jours.</strong> Le Lorne allie confort et style et s'adapte à toutes les situations : du bureau au week-end, de la ville à la nature. Il est assez compact pour se porter légèrement toute la journée tout en accueillant tout ce que vous emportez au quotidien.</p><p>À l'intérieur, vous trouvez un compartiment matelassé pour ordinateur portable, un grand compartiment principal et des poches pour vos accessoires. La poche avant garde les petits objets à portée de main. Les bretelles rembourrées et réglables se portent confortablement, même avec un sac bien rempli. Le coloris cognac chaleureux du cuir à tannage végétal développe une belle patine à l'usage.</p><h3>Caractéristiques du sac à dos Beocca Lorne</h3><ul><li>Petit sac à dos compact de 26 x 30 x 8 cm</li><li>Compartiment matelassé pour ordinateur portable</li><li>Grand compartiment principal avec poches intérieures pour accessoires</li><li>Poche avant pour les petits objets</li><li>Bretelles réglables et rembourrées</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Vous cherchez un petit sac à dos en cuir pour femme qui convient à toutes les occasions, des réunions professionnelles aux sorties décontractées ? Le Lorne en cognac est un choix intemporel.</p>`,
    },
  },

  'portemonnee-yarra': {
    model: 'Yarra',
    colours: { 'Cognac': { nl: 'Cognac', fr: 'Cognac' }, 'Antraciet': { nl: 'Antraciet', fr: 'Anthracite' } },
    nl: {
      title: v => `Beocca Yarra Leren Portemonnee Dames - Ruime Overslagportemonnee met Muntvak met Rits - Plantaardig Gelooid Leer - 18 x 10 x 3 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Yarra, ruime leren portemonnee voor alles wat je bij je draagt.</strong> Ben jij iemand die geen bonnetje, pasje of muntje achterlaat? Dan is deze ruime dames portemonnee van plantaardig gelooid leer voor jou gemaakt. Met veel vakjes, een apart muntvak met rits en ruimte voor briefgeld blijft alles georganiseerd.</p><p>Waar minimalistische portemonnees beperken, biedt de Yarra vrijheid: meerdere kaartsleuven voor je pasjes en klantenkaarten, een ruim muntvak met stevige rits, biljettenvakken voor briefgeld of bonnetjes en een vak voor je rijbewijs of identiteitskaart. Ondanks de ruime capaciteit blijft het formaat van 18 x 10 x 3 cm praktisch en past hij in de meeste handtassen.</p><h3>Kenmerken van de Beocca Yarra portemonnee</h3><ul><li>Overslagmodel met ruimte voor 12 pasjes, briefgeld en munten</li><li>Apart muntvak met stevige rits</li><li>Biljettenvakken voor briefgeld en bonnetjes</li><li>Vak voor rijbewijs of identiteitskaart</li><li>Afmetingen 18 x 10 x 3 cm</li><li>100% plantaardig gelooid leer met verstevigde naden, handgemaakt</li></ul>${NL_LEER}<p>Een portemonnee pak je tientallen keren per dag vast. Het zachte plantaardig gelooide leer van de Yarra voelt prettig aan en wordt met gebruik alleen maar soepeler. Verkrijgbaar in cognac en antraciet. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Yarra Portefeuille en Cuir Femme - Grand Portefeuille à Rabat avec Porte-Monnaie Zippé - Cuir à Tannage Végétal - 18 x 10 x 3 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Yarra, grand portefeuille en cuir pour tout ce que vous emportez.</strong> Vous ne laissez jamais un ticket, une carte ou une pièce derrière vous ? Ce grand portefeuille femme en cuir à tannage végétal est fait pour vous. Avec ses nombreux compartiments, son porte-monnaie zippé séparé et sa place pour les billets, tout reste bien organisé.</p><p>Là où les portefeuilles minimalistes limitent, le Yarra offre de la liberté : plusieurs emplacements pour vos cartes bancaires et de fidélité, un porte-monnaie spacieux à fermeture éclair solide, des compartiments pour les billets ou les reçus et un emplacement pour votre permis ou carte d'identité. Malgré sa grande capacité, son format de 18 x 10 x 3 cm reste pratique et se glisse dans la plupart des sacs à main.</p><h3>Caractéristiques du portefeuille Beocca Yarra</h3><ul><li>Modèle à rabat avec place pour 12 cartes, billets et pièces</li><li>Porte-monnaie séparé à fermeture éclair solide</li><li>Compartiments pour billets et reçus</li><li>Emplacement pour permis ou carte d'identité</li><li>Dimensions 18 x 10 x 3 cm</li><li>Cuir 100 % à tannage végétal aux coutures renforcées, fait main</li></ul>${FR_CUIR}<p>Un portefeuille, on le prend en main des dizaines de fois par jour. Le cuir souple à tannage végétal du Yarra est agréable au toucher et s'assouplit encore à l'usage. Disponible en cognac et anthracite. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'kaarthouder-argyle': {
    model: 'Argyle',
    colours: { 'Bruin': { nl: 'Bruin', fr: 'Marron' }, 'Antraciet': { nl: 'Antraciet', fr: 'Anthracite' } },
    nl: {
      title: v => `Beocca Argyle Leren Kaarthouder Dames Heren - Compacte Pasjeshouder voor 6 Pasjes - Creditcardhouder op Creditcardformaat - Plantaardig Gelooid Leer - ${v.nl}`,
      desc: v => `<p><strong>Beocca Argyle, compacte leren kaarthouder voor dagelijks gebruik.</strong> De Argyle past bij een moderne, minimalistische levensstijl. Ontworpen op creditcardformaat glijdt hij moeiteloos in je broekzak, binnenzak of tas zonder op te vallen of in de weg te zitten.</p><p>Met ruimte voor 6 pasjes in aparte vakjes en een extra vak voor bonnetjes, visitekaartjes of briefgeld heb je alles wat je dagelijks nodig hebt binnen handbereik. Of je nu boodschappen doet, uit eten gaat of op reis bent: deze pasjeshouder houdt je essentiële zaken georganiseerd en toegankelijk.</p><h3>Kenmerken van de Beocca Argyle kaarthouder</h3><ul><li>Compact creditcardformaat van 7 x 7 x 1 cm</li><li>Ruimte voor 6 pasjes in aparte vakjes</li><li>Extra vak voor bonnetjes, visitekaartjes of briefgeld</li><li>Minimalistisch en tijdloos design</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Reis je liever licht en draag je alleen het noodzakelijke bij je? Dan is de Argyle een slanke creditcardhouder die precies doet wat hij moet doen, voor dames en heren. Ook een mooi cadeau voor wie kwaliteit en eenvoud waardeert. Verkrijgbaar in bruin en antraciet. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Argyle Porte-Cartes en Cuir Femme Homme - Porte-Cartes Compact pour 6 Cartes - Format Carte de Crédit - Cuir à Tannage Végétal - ${v.fr}`,
      desc: v => `<p><strong>Beocca Argyle, porte-cartes en cuir compact pour tous les jours.</strong> L'Argyle s'inscrit dans un mode de vie moderne et minimaliste. Conçu au format carte de crédit, il se glisse sans effort dans une poche de pantalon, une poche intérieure ou un sac, sans se faire remarquer ni gêner.</p><p>Avec de la place pour 6 cartes dans des compartiments séparés et un compartiment supplémentaire pour les reçus, cartes de visite ou billets, vous avez l'essentiel du quotidien à portée de main. Pour les courses, un dîner ou un voyage, ce porte-cartes garde vos indispensables organisés et accessibles.</p><h3>Caractéristiques du porte-cartes Beocca Argyle</h3><ul><li>Format compact carte de crédit de 7 x 7 x 1 cm</li><li>Place pour 6 cartes dans des compartiments séparés</li><li>Compartiment supplémentaire pour reçus, cartes de visite ou billets</li><li>Design minimaliste et intemporel</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Vous préférez voyager léger et n'emporter que l'essentiel ? L'Argyle est un porte-cartes fin qui fait exactement ce qu'il doit faire, pour femme et homme. C'est aussi un beau cadeau pour qui apprécie la qualité et la simplicité. Disponible en marron et anthracite. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'rugzak-bryce-cognac-17': {
    model: 'Bryce',
    colours: { 'Cognac': { nl: 'Cognac', fr: 'Cognac' }, 'Zwart': { nl: 'Zwart', fr: 'Noir' } },
    nl: {
      title: v => `Beocca Bryce Leren Rugzak Dames Heren - Laptoptas 17 inch - Laptop Rugtas met Organizer en Gevoerd Laptopvak - Plantaardig Gelooid Leer - 25 liter - ${v.nl}`,
      desc: v => `<p><strong>Beocca Bryce, ruime leren rugzak voor 17 inch laptops.</strong> Met de Bryce wil je gezien worden. Deze ruime leren rugzak combineert een stoere, onmiskenbare uitstraling met praktisch gebruiksgemak. Het ruime hoofdvak biedt plaats aan laptops tot 17 inch, terwijl de slimme vakverdeling ervoor zorgt dat al je spullen overzichtelijk en bereikbaar blijven.</p><p>Het gevoerde laptopvak absorbeert schokken en voorkomt krassen. Het hoofdvak heeft een organizer, het voorvak met rits is ideaal voor telefoon, portemonnee en sleutels. De gevoerde, verstelbare schouderbanden verdelen het gewicht gelijkmatig, ook bij langere dagen onderweg. Verstevigde naden en stevige hardware maken de Bryce klaar voor jarenlang dagelijks gebruik.</p><h3>Kenmerken van de Beocca Bryce rugzak</h3><ul><li>Gevoerd laptopvak voor laptops tot 17 inch</li><li>Afmetingen 29 x 43 x 12 cm, inhoud 25 liter</li><li>Ruim hoofdvak met organizer</li><li>Voorvak met rits voor telefoon, portemonnee en sleutels</li><li>Verstelbare, gevoerde schouderbanden</li><li>Katoenen binnenvoering, verstevigde naden en stevige hardware</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Van werk naar vrije tijd, van studie naar reizen: de Bryce is een leren laptop rugzak voor dames en heren die bij elke gelegenheid past. Verkrijgbaar in cognac en zwart. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Bryce Sac à Dos en Cuir Femme Homme - Sac Ordinateur 17 Pouces - Compartiment Matelassé et Organiseur - Cuir à Tannage Végétal - 25 litres - ${v.fr}`,
      desc: v => `<p><strong>Beocca Bryce, grand sac à dos en cuir pour ordinateur 17 pouces.</strong> Avec le Bryce, vous ne passez pas inaperçu. Ce sac à dos spacieux en cuir allie une allure robuste et affirmée à une grande praticité. Le grand compartiment principal accueille les ordinateurs portables jusqu'à 17 pouces, tandis que l'agencement intelligent garde toutes vos affaires organisées et accessibles.</p><p>Le compartiment matelassé absorbe les chocs et évite les rayures. Le compartiment principal est équipé d'un organiseur, la poche avant zippée est idéale pour téléphone, portefeuille et clés. Les bretelles rembourrées et réglables répartissent le poids de façon homogène, même lors de longues journées. Coutures renforcées et quincaillerie solide préparent le Bryce à des années d'usage quotidien.</p><h3>Caractéristiques du sac à dos Beocca Bryce</h3><ul><li>Compartiment matelassé pour ordinateur portable jusqu'à 17 pouces</li><li>Dimensions 29 x 43 x 12 cm, volume de 25 litres</li><li>Grand compartiment principal avec organiseur</li><li>Poche avant zippée pour téléphone, portefeuille et clés</li><li>Bretelles réglables et rembourrées</li><li>Doublure en coton, coutures renforcées et quincaillerie solide</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Du travail aux loisirs, des études aux voyages : le Bryce est un sac à dos en cuir pour ordinateur, pour femme et homme, qui convient à toutes les occasions. Disponible en cognac et noir. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'rugzak-finn': {
    model: 'Finn',
    colours: { 'Groen': { nl: 'Groen', fr: 'Vert' }, 'Zwart': { nl: 'Zwart', fr: 'Noir' } },
    nl: {
      title: v => `Beocca Finn Rugzak Leer en Canvas Dames Heren - Laptoptas 17 inch - Lichtgewicht Laptop Rugtas met Gevoerd Laptopvak - Plantaardig Gelooid Leer - 25 liter - ${v.nl}`,
      desc: v => `<p><strong>Beocca Finn, stoere rugzak van leer en canvas voor 17 inch laptops.</strong> De Finn combineert functionaliteit met een robuuste uitstraling. Het canvas houdt het gewicht laag, het plantaardig gelooide leer op de flap, de banden en de bodem zorgt voor stevigheid en karakter. Met ruimte voor laptops tot 17 inch en tal van praktische vakken is de Finn de ideale metgezel voor werk, studie of avontuur.</p><p>Het gevoerde laptopvak beschermt je laptop, het ruime hoofdvak heeft een organizer en meerdere buitenvakken geven snelle toegang tot je spullen. De verstelbare, gevoerde schouderbanden verdelen het gewicht en de verstevigde bodem en naden maken hem klaar voor jarenlang intensief gebruik. Bij de Finn wordt een leren etui meegeleverd.</p><h3>Kenmerken van de Beocca Finn rugzak</h3><ul><li>Gevoerd laptopvak voor laptops tot 17 inch</li><li>Afmetingen 35 x 40 x 12 cm, inhoud 25 liter</li><li>Lichtgewicht combinatie van canvas en plantaardig gelooid leer</li><li>Ruim hoofdvak met organizer en meerdere buitenvakken</li><li>Verstelbare, gevoerde schouderbanden</li><li>Verstevigde bodem en naden, inclusief leren etui</li></ul>${NL_LEER}<p>De ruige uitstraling van de Finn wordt alleen maar beter met de tijd: elke kras en elk gebruiksspoor draagt bij aan het karakter. Verkrijgbaar in groen en zwart. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Finn Sac à Dos Cuir et Toile Femme Homme - Sac Ordinateur 17 Pouces - Sac à Dos Léger avec Compartiment Matelassé - Cuir à Tannage Végétal - 25 litres - ${v.fr}`,
      desc: v => `<p><strong>Beocca Finn, sac à dos robuste en cuir et toile pour ordinateur 17 pouces.</strong> Le Finn allie fonctionnalité et allure robuste. La toile garde le poids bas, le cuir à tannage végétal du rabat, des sangles et du fond apporte solidité et caractère. Avec de la place pour un ordinateur portable jusqu'à 17 pouces et de nombreuses poches pratiques, le Finn est le compagnon idéal pour le travail, les études ou l'aventure.</p><p>Le compartiment matelassé protège votre ordinateur, le grand compartiment principal dispose d'un organiseur et plusieurs poches extérieures donnent un accès rapide à vos affaires. Les bretelles réglables et rembourrées répartissent le poids, le fond et les coutures renforcés le préparent à des années d'usage intensif. Un étui en cuir est livré avec le Finn.</p><h3>Caractéristiques du sac à dos Beocca Finn</h3><ul><li>Compartiment matelassé pour ordinateur portable jusqu'à 17 pouces</li><li>Dimensions 35 x 40 x 12 cm, volume de 25 litres</li><li>Association légère de toile et de cuir à tannage végétal</li><li>Grand compartiment principal avec organiseur et plusieurs poches extérieures</li><li>Bretelles réglables et rembourrées</li><li>Fond et coutures renforcés, étui en cuir inclus</li></ul>${FR_CUIR}<p>L'allure brute du Finn se bonifie avec le temps : chaque rayure et chaque trace d'usage ajoute à son caractère. Disponible en vert et noir. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'rugzak-lilith': {
    model: 'Lilith',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' } },
    nl: {
      title: v => `Beocca Lilith Leren Rugzak Dames Heren - Vintage Rugtas met Ruimte voor Laptop tot 13 inch - Plantaardig Gelooid Leer - 20 liter - ${v.nl}`,
      desc: v => `<p><strong>Beocca Lilith, leren rugzak met vintage uitstraling.</strong> Lilith ademt de charme van vroeger met een knipoog naar het nu. Deze stijlvolle leren rugzak combineert vintage vibes met modern gemak: een ontwerp dat opvalt zonder te schreeuwen. Het ontwerp is geïnspireerd op klassieke rugzakken uit vroegere decennia, met de functionaliteit die je vandaag verwacht.</p><p>Verstelbare schouderbanden zorgen voor comfort, praktische binnenvakken voor organisatie en een stevige sluiting voor veiligheid. Met een formaat van 35 x 40 x 12 cm en een inhoud van 20 liter is er ruimte voor een laptop tot 13 inch, boeken en je dagelijkse spullen. De klassieke zwarte kleur past bij vrijwel elke outfit, van casual tot semi-formeel.</p><h3>Kenmerken van de Beocca Lilith rugzak</h3><ul><li>Vintage geïnspireerd design</li><li>Afmetingen 35 x 40 x 12 cm, inhoud 20 liter</li><li>Ruimte voor een laptop tot 13 inch</li><li>Meerdere binnenvakken voor organisatie</li><li>Verstelbare schouderbanden en stevige sluiting</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Met de Lilith kies je voor vakmanschap boven massaproductie en voor tijdloos boven trendy. Een leren rugzak voor dames en heren die jarenlang je trouwe metgezel is.</p>`,
    },
    fr: {
      title: v => `Beocca Lilith Sac à Dos en Cuir Femme Homme - Sac à Dos Vintage avec Place pour Ordinateur jusqu'à 13 Pouces - Cuir à Tannage Végétal - 20 litres - ${v.fr}`,
      desc: v => `<p><strong>Beocca Lilith, sac à dos en cuir au look vintage.</strong> Le Lilith respire le charme d'autrefois avec un clin d'œil au présent. Ce sac à dos élégant en cuir associe une allure vintage au confort moderne : un design qui attire le regard sans crier. Il s'inspire des sacs à dos classiques des décennies passées, avec la fonctionnalité que vous attendez aujourd'hui.</p><p>Les bretelles réglables assurent le confort, les poches intérieures l'organisation et la fermeture solide la sécurité. Avec un format de 35 x 40 x 12 cm et un volume de 20 litres, il accueille un ordinateur portable jusqu'à 13 pouces, des livres et vos affaires du quotidien. Le noir classique s'accorde avec presque toutes les tenues, du décontracté au semi-formel.</p><h3>Caractéristiques du sac à dos Beocca Lilith</h3><ul><li>Design d'inspiration vintage</li><li>Dimensions 35 x 40 x 12 cm, volume de 20 litres</li><li>Place pour un ordinateur portable jusqu'à 13 pouces</li><li>Plusieurs poches intérieures pour l'organisation</li><li>Bretelles réglables et fermeture solide</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Avec le Lilith, vous choisissez l'artisanat plutôt que la production de masse et l'intemporel plutôt que la tendance. Un sac à dos en cuir pour femme et homme qui vous accompagne fidèlement pendant des années.</p>`,
    },
  },

  'weekendtas-milo': {
    model: 'Milo',
    colours: { 'Groen': { nl: 'Groen', fr: 'Vert' }, 'Cognac': { nl: 'Cognac', fr: 'Cognac' } },
    nl: {
      title: v => `Beocca Milo Leren Weekendtas Dames Heren - Reistas Handbagage 55 x 27 x 25 cm - Duffel Bag met Afneembare Schouderband - Plantaardig Gelooid Leer - ${v.nl}`,
      desc: v => `<p><strong>Beocca Milo, ruime leren weekendtas als handbagage.</strong> Of je nu een spontaan weekendje weg gaat, een zakenreis plant of gewoon graag voorbereid bent: deze leren reistas is je metgezel. De Milo is ruim genoeg voor een paar dagen kleding en persoonlijke spullen, maar met 55 x 27 x 25 cm compact genoeg om als handbagage mee te nemen op vliegreizen.</p><p>De brede opening maakt in- en uitpakken makkelijk en de binnenvakken houden je spullen georganiseerd. De verstevigde bodem zorgt dat de tas netjes rechtop blijft staan, ook halfvol. Je draagt hem aan de stevige hengsels of met de afneembare schouderband, zodat het gewicht ook over langere afstanden comfortabel verdeeld wordt. Het hoofdvak sluit met een rits.</p><h3>Kenmerken van de Beocca Milo weekendtas</h3><ul><li>Afmetingen 55 x 27 x 25 cm, geschikt als handbagage</li><li>Ruim hoofdvak voor 2 tot 3 dagen kleding</li><li>Brede opening en binnenvakken voor organisatie</li><li>Verstevigde bodem die rechtop blijft staan</li><li>Stevige hengsels en afneembare schouderband</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Elke reis draagt bij aan het karakter van deze leren duffel bag. Een weekendtas voor dames en heren, verkrijgbaar in groen en cognac. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Milo Sac Week-end en Cuir Femme Homme - Sac de Voyage Bagage Cabine 55 x 27 x 25 cm - Sac Duffel avec Bandoulière Amovible - Cuir à Tannage Végétal - ${v.fr}`,
      desc: v => `<p><strong>Beocca Milo, grand sac week-end en cuir au format bagage cabine.</strong> Escapade improvisée, voyage d'affaires ou simple envie d'être prêt : ce sac de voyage en cuir vous accompagne. Le Milo est assez spacieux pour quelques jours de vêtements et d'effets personnels, mais avec ses 55 x 27 x 25 cm il reste assez compact pour voyager en cabine.</p><p>La large ouverture facilite le rangement et les poches intérieures gardent vos affaires organisées. Le fond renforcé maintient le sac bien droit, même à moitié rempli. Vous le portez par ses poignées solides ou avec la bandoulière amovible, pour répartir le poids confortablement sur les longues distances. Le compartiment principal se ferme par une fermeture éclair.</p><h3>Caractéristiques du sac week-end Beocca Milo</h3><ul><li>Dimensions 55 x 27 x 25 cm, format bagage à main</li><li>Grand compartiment principal pour 2 à 3 jours de vêtements</li><li>Large ouverture et poches intérieures pour l'organisation</li><li>Fond renforcé qui tient droit</li><li>Poignées solides et bandoulière amovible</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Chaque voyage ajoute au caractère de ce sac duffel en cuir. Un sac week-end pour femme et homme, disponible en vert et cognac. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'schoudertas-ivy': {
    model: 'Ivy',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Cognac': { nl: 'Cognac', fr: 'Cognac' } },
    nl: {
      title: v => `Beocca Ivy Leren Schoudertas Dames - Crossbody Tas met Ruimte voor iPad of Tablet tot 10 inch - Plantaardig Gelooid Leer - 29 x 23 x 8 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Ivy, stijlvolle leren schoudertas met ruimte voor je iPad.</strong> De Ivy combineert het perfecte formaat met praktische functionaliteit. Met ruimte voor een iPad, tablet of kleine laptop tot 10 inch plus een notitieboek en documenten is deze crossbody tas ideaal voor wie onderweg productief wil blijven: in het koffiehuis, in de trein of op kantoor.</p><p>Binnenvakken houden je telefoon en portemonnee gescheiden en snel binnen handbereik. De brede, verstelbare schouderband snijdt niet in je schouder en maakt crossbody dragen de hele dag comfortabel. De stevige magneetsluiting houdt je spullen veilig. Niet te groot, niet te klein: 29 x 23 x 8 cm.</p><h3>Kenmerken van de Beocca Ivy schoudertas</h3><ul><li>Hoofdvak voor iPad, tablet of kleine laptop tot 10 inch</li><li>Ruimte voor notitieboek en documenten</li><li>Binnenvakken voor telefoon en portemonnee</li><li>Brede, verstelbare schouderband voor crossbody dragen</li><li>Afmetingen 29 x 23 x 8 cm, magneetsluiting</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Professioneel en casual tegelijk: de Ivy is een leren crossbody tas voor dames die bij elk type outfit past. Verkrijgbaar in zwart en cognac. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Ivy Sac Bandoulière Femme en Cuir - Sac Crossbody avec Place pour iPad ou Tablette jusqu'à 10 Pouces - Cuir à Tannage Végétal - 29 x 23 x 8 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Ivy, élégant sac bandoulière en cuir avec place pour votre iPad.</strong> L'Ivy allie le format idéal à une vraie fonctionnalité. Avec de la place pour un iPad, une tablette ou un petit ordinateur jusqu'à 10 pouces, plus un carnet et des documents, ce sac crossbody est parfait pour rester productif en déplacement : au café, dans le train ou au bureau.</p><p>Les poches intérieures séparent votre téléphone et votre portefeuille et les gardent à portée de main. La bandoulière large et réglable ne cisaille pas l'épaule et rend le port crossbody confortable toute la journée. La fermeture magnétique solide garde vos affaires en sécurité. Ni trop grand, ni trop petit : 29 x 23 x 8 cm.</p><h3>Caractéristiques du sac bandoulière Beocca Ivy</h3><ul><li>Compartiment principal pour iPad, tablette ou petit ordinateur jusqu'à 10 pouces</li><li>Place pour un carnet et des documents</li><li>Poches intérieures pour téléphone et portefeuille</li><li>Bandoulière large et réglable pour un port crossbody</li><li>Dimensions 29 x 23 x 8 cm, fermeture magnétique</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Professionnel et décontracté à la fois : l'Ivy est un sac crossbody en cuir pour femme qui s'accorde avec toutes les tenues. Disponible en noir et cognac. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'leren-schoudertas-niba': {
    model: 'Niba',
    colours: { 'Groen': { nl: 'Groen', fr: 'Vert' }, 'Cognac': { nl: 'Cognac', fr: 'Cognac' } },
    nl: {
      title: v => `Beocca Niba Leren Schoudertas Dames - Compacte Crossbody Tas met Magneetsluiting en Ritsvak - Plantaardig Gelooid Leer - 20 x 20 x 6 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Niba, veelzijdige leren schoudertas voor elke dag.</strong> De Niba past zich aan jouw dag aan. Of je nu naar kantoor gaat, afspreekt met vrienden of een stedentrip maakt, deze compacte schoudertas is er klaar voor. Groot genoeg voor werk, compact genoeg voor vrije tijd: het formaat van 20 x 20 x 6 cm is precies goed voor je dagelijkse essentials en wat extra.</p><p>Het ruime hoofdvak heeft binnenvakken voor telefoon en portemonnee en een apart ritsvak voor waardevolle spullen. De tas sluit met een magneetsluiting en heeft een katoenen binnenvoering. De brede, verstelbare schouderband snijdt niet in je schouder, ook niet na een lange dag.</p><h3>Kenmerken van de Beocca Niba schoudertas</h3><ul><li>Afmetingen 20 x 20 x 6 cm</li><li>Ruim hoofdvak met binnenvakken voor telefoon en portemonnee</li><li>Apart ritsvak voor waardevolle spullen</li><li>Brede, verstelbare schouderband</li><li>Magneetsluiting en katoenen binnenvoering</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Van kantoor tot terras, van museum tot markt: de Niba is de leren crossbody tas voor dames die je steeds weer pakt. Verkrijgbaar in groen en cognac. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Niba Sac Bandoulière Femme en Cuir - Petit Sac Crossbody avec Fermeture Magnétique et Poche Zippée - Cuir à Tannage Végétal - 20 x 20 x 6 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Niba, sac bandoulière en cuir polyvalent pour tous les jours.</strong> Le Niba s'adapte à votre journée. Au bureau, entre amis ou en city trip, ce petit sac bandoulière est prêt. Assez grand pour le travail, assez compact pour les loisirs : son format de 20 x 20 x 6 cm est juste ce qu'il faut pour vos essentiels du quotidien et un peu plus.</p><p>Le compartiment principal spacieux dispose de poches intérieures pour téléphone et portefeuille et d'une poche zippée séparée pour vos objets de valeur. Le sac se ferme par un aimant et est doublé de coton. La bandoulière large et réglable ne cisaille pas l'épaule, même après une longue journée.</p><h3>Caractéristiques du sac bandoulière Beocca Niba</h3><ul><li>Dimensions 20 x 20 x 6 cm</li><li>Compartiment principal spacieux avec poches pour téléphone et portefeuille</li><li>Poche zippée séparée pour les objets de valeur</li><li>Bandoulière large et réglable</li><li>Fermeture magnétique et doublure en coton</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Du bureau à la terrasse, du musée au marché : le Niba est le sac crossbody en cuir pour femme que vous reprenez chaque jour. Disponible en vert et cognac. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'maia': {
    model: 'Maia',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Beige': { nl: 'Beige', fr: 'Beige' }, 'Donkerbruin': { nl: 'Donkerbruin', fr: 'Marron foncé' } },
    nl: {
      title: v => `Beocca Maia Leren Schoudertas Dames - Lichte Crossbody Tas met Twee Schouderbanden - Plantaardig Gelooid Leer - 24 x 15 x 7 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Maia, lichte leren schoudertas voor dagelijks gebruik.</strong> De Maia neem je makkelijk mee naar elke gelegenheid. Licht genoeg om de hele dag comfortabel te dragen, maar met 24 x 15 x 7 cm ruim genoeg voor je portemonnee, telefoon, sleutels en make-up. De tas wordt geleverd met twee schouderbanden: een korte, deels gevlochten band en een lange, verstelbare band om haar als crossbody tas te dragen.</p><p>Meerdere binnenvakjes houden je spullen overzichtelijk. De tas sluit met een gesp, magneet en een YKK rits. Het plantaardig gelooide leer geeft de Maia een warme, natuurlijke uitstraling die bij vrijwel elke outfit past, van casual tot chic.</p><h3>Kenmerken van de Beocca Maia schoudertas</h3><ul><li>Afmetingen 24 x 15 x 7 cm, lichtgewicht</li><li>Twee schouderbanden: kort en deels gevlochten, lang en verstelbaar voor crossbody</li><li>Meerdere binnenvakjes voor organisatie</li><li>Sluiting met gesp, magneet en YKK rits</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Van de ochtendspits naar kantoor, van een lunchafspraak naar een avondje uit: de Maia is een leren schoudertas voor dames met een tijdloos ontwerp dat niet veroudert. Verkrijgbaar in zwart, beige en donkerbruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Maia Sac Bandoulière Femme en Cuir - Sac Crossbody Léger avec Deux Bandoulières - Cuir à Tannage Végétal - 24 x 15 x 7 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Maia, sac bandoulière en cuir léger pour tous les jours.</strong> Le Maia vous suit partout sans effort. Assez léger pour se porter confortablement toute la journée, mais avec ses 24 x 15 x 7 cm assez spacieux pour votre portefeuille, téléphone, clés et maquillage. Le sac est livré avec deux bandoulières : une courte, partiellement tressée, et une longue, réglable, pour le porter en crossbody.</p><p>Plusieurs poches intérieures gardent vos affaires organisées. Le sac se ferme par une boucle, un aimant et une fermeture éclair YKK. Le cuir à tannage végétal donne au Maia une allure chaleureuse et naturelle qui s'accorde avec presque toutes les tenues, du décontracté au chic.</p><h3>Caractéristiques du sac bandoulière Beocca Maia</h3><ul><li>Dimensions 24 x 15 x 7 cm, léger</li><li>Deux bandoulières : courte et partiellement tressée, longue et réglable pour le crossbody</li><li>Plusieurs poches intérieures pour l'organisation</li><li>Fermeture par boucle, aimant et glissière YKK</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>De l'heure de pointe au bureau, du déjeuner à la soirée : le Maia est un sac bandoulière en cuir pour femme au design intemporel. Disponible en noir, beige et marron foncé. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'fei': {
    model: 'Fei',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Beige': { nl: 'Beige', fr: 'Beige' }, 'Donkerbruin': { nl: 'Donkerbruin', fr: 'Marron foncé' } },
    nl: {
      title: v => `Beocca Fei Leren Schoudertas Dames - Compacte Crossbody Tas met Magneetsluiting en YKK Rits - Plantaardig Gelooid Leer - 24 x 18 x 9 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Fei, compacte leren schoudertas met tijdloze elegantie.</strong> De Fei combineert tijdloze elegantie met praktisch gemak, ontworpen voor vrouwen die een stijlvolle tas willen zonder onnodige bulk. Het compacte formaat van 24 x 18 x 9 cm is ideaal voor je essentiële spullen: telefoon, portemonnee, sleutels en een lippenstift.</p><p>Dankzij de verstelbare schouderband draag je de Fei over de schouder, crossbody of kort in de hand. De stevige magneetsluiting en de YKK rits houden alles op zijn plek, de binnenvakverdeling zorgt voor overzicht. Licht en onopvallend: je vergeet dat je haar draagt, totdat je iets nodig hebt.</p><h3>Kenmerken van de Beocca Fei schoudertas</h3><ul><li>Compact formaat van 24 x 18 x 9 cm</li><li>Verstelbare schouderband: schouder, crossbody of in de hand</li><li>Stevige magneetsluiting en YKK rits</li><li>Binnenvakverdeling voor overzicht</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Elegant genoeg voor feestjes en gelegenheden, praktisch genoeg voor elke dag: de Fei is een kleine leren crossbody tas voor dames zonder trends en zonder veroudering. Verkrijgbaar in zwart, beige en donkerbruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Fei Sac Bandoulière Femme en Cuir - Petit Sac Crossbody avec Fermeture Magnétique et Glissière YKK - Cuir à Tannage Végétal - 24 x 18 x 9 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Fei, petit sac bandoulière en cuir à l'élégance intemporelle.</strong> Le Fei allie élégance intemporelle et praticité, pensé pour les femmes qui veulent un sac élégant sans volume inutile. Son format compact de 24 x 18 x 9 cm est idéal pour l'essentiel : téléphone, portefeuille, clés et un rouge à lèvres.</p><p>Grâce à la bandoulière réglable, vous portez le Fei à l'épaule, en crossbody ou à la main. La fermeture magnétique solide et la glissière YKK gardent tout en place, les compartiments intérieurs assurent l'organisation. Léger et discret : vous oubliez que vous le portez, jusqu'à ce que vous ayez besoin de quelque chose.</p><h3>Caractéristiques du sac bandoulière Beocca Fei</h3><ul><li>Format compact de 24 x 18 x 9 cm</li><li>Bandoulière réglable : épaule, crossbody ou à la main</li><li>Fermeture magnétique solide et glissière YKK</li><li>Compartiments intérieurs pour l'organisation</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Assez élégant pour les soirées et les occasions, assez pratique pour tous les jours : le Fei est un petit sac crossbody en cuir pour femme, sans tendance ni vieillissement. Disponible en noir, beige et marron foncé. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'beau': {
    model: 'Beau',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Beige': { nl: 'Beige', fr: 'Beige' }, 'Donkerbruin': { nl: 'Donkerbruin', fr: 'Marron foncé' } },
    nl: {
      title: v => `Beocca Beau Leren Handtas Dames - Mid-size Schoudertas met Gevlochten Handvatten en Verstelbare Schouderband - Plantaardig Gelooid Leer - 28 x 22 x 12 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Beau, verfijnde leren handtas in mid-size formaat.</strong> De Beau combineert stijl en functionaliteit moeiteloos. Met haar elegante, vrouwelijke uitstraling en praktische indeling is ze de ideale metgezel voor vrouwen die waarde hechten aan kwaliteit en design. Het mid-size formaat van 28 x 22 x 12 cm is zorgvuldig gekozen: groot genoeg voor portemonnee, telefoon, sleutels, make-up, een waterfles en een paraplu, maar compact genoeg om niet onhandig te worden.</p><p>De gevlochten leren handvatten en de goudkleurige hardware geven de Beau haar karakter. Met de verstelbare schouderband draag je haar ook over de schouder. De praktische binnenvakverdeling houdt alles op zijn plek en de stevige YKK rits sluit de tas veilig af. Het soepele leer past zich aan naar jouw gebruik.</p><h3>Kenmerken van de Beocca Beau handtas</h3><ul><li>Mid-size formaat van 28 x 22 x 12 cm</li><li>Gevlochten leren handvatten en goudkleurige hardware</li><li>Verstelbare schouderband</li><li>Praktische binnenvakverdeling</li><li>Stevige YKK rits</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Van ochtend tot avond: de Beau past bij casual jeans én elegante avondkleding. Een leren handtas voor dames die na een jaar letterlijk anders is dan elke andere. Verkrijgbaar in zwart, beige en donkerbruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Beau Sac à Main en Cuir Femme - Sac Porté Épaule Taille Moyenne avec Anses Tressées et Bandoulière Réglable - Cuir à Tannage Végétal - 28 x 22 x 12 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Beau, sac à main en cuir raffiné au format mid-size.</strong> Le Beau allie style et fonctionnalité sans effort. Avec son allure élégante et féminine et son agencement pratique, c'est le compagnon idéal des femmes qui tiennent à la qualité et au design. Son format de 28 x 22 x 12 cm est soigneusement choisi : assez grand pour portefeuille, téléphone, clés, maquillage, une bouteille d'eau et un parapluie, assez compact pour rester maniable.</p><p>Les anses tressées en cuir et la quincaillerie dorée donnent au Beau son caractère. Avec la bandoulière réglable, vous le portez aussi à l'épaule. Les compartiments intérieurs gardent tout à sa place et la solide fermeture éclair YKK ferme le sac en toute sécurité. Le cuir souple s'adapte à votre usage.</p><h3>Caractéristiques du sac à main Beocca Beau</h3><ul><li>Format mid-size de 28 x 22 x 12 cm</li><li>Anses tressées en cuir et quincaillerie dorée</li><li>Bandoulière réglable</li><li>Compartiments intérieurs pratiques</li><li>Solide fermeture éclair YKK</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Du matin au soir : le Beau s'accorde avec un jean décontracté comme avec une tenue de soirée. Un sac à main en cuir pour femme qui, après un an, ne ressemble à aucun autre. Disponible en noir, beige et marron foncé. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'mira': {
    model: 'Mira',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir', nlMat: 'glad leer', frMat: 'cuir lisse', suede: false }, 'Donkerbruin': { nl: 'Donkerbruin', fr: 'Marron foncé', nlMat: 'glad leer', frMat: 'cuir lisse', suede: false }, 'Suede Zwart': { nl: 'Suède Zwart', fr: 'Daim Noir', nlMat: 'suède', frMat: 'daim', suede: true } },
    nl: {
      title: v => `Beocca Mira ${v.suede ? 'Suède' : 'Leren'} Shopper Dames - Grote Tas met Ruimte voor Laptop tot 15 inch - Laptoptas en Werktas - Plantaardig Gelooid Leer - 30 x 35 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Mira, ruime leren shopper voor werk en vrije tijd.</strong> De Mira gaat moeiteloos mee van werk naar vrije tijd. Met haar klassieke silhouet en praktische afmetingen van 30 x 35 cm is ze de tas voor vrouwen die veel te dragen hebben maar geen concessies willen doen aan stijl. Laptop tot 15 inch, A4-documenten, lunch, sportkleding: het past er allemaal in.</p><p>Binnenvakken voor telefoon en portemonnee en een ritsvak voor waardevolle spullen houden alles overzichtelijk. De tas sluit met een magneetsluiting. De verstevigde bodem zorgt dat de Mira op zichzelf blijft staan en de stevige handvatten dragen comfortabel, ook tijdens een lange werkdag. Deze uitvoering is gemaakt van ${v.nlMat} in de kleur ${v.nl.toLowerCase()}.</p><h3>Kenmerken van de Beocca Mira shopper</h3><ul><li>Afmetingen 30 x 35 cm</li><li>Ruim hoofdvak met ruimte voor een laptop tot 15 inch en A4</li><li>Binnenvakken voor telefoon en portemonnee</li><li>Ritsvak voor waardevolle spullen, magneetsluiting</li><li>Verstevigde bodem en stevige handvatten</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Van boardroom tot boodschappen: de Mira is een grote leren shopper voor dames met een tijdloos design dat nooit uit de mode raakt. Verkrijgbaar in zwart, donkerbruin en suède zwart.</p>`,
    },
    fr: {
      title: v => `Beocca Mira Sac Cabas en ${v.suede ? 'Daim' : 'Cuir'} Femme - Grand Sac avec Place pour Ordinateur jusqu'à 15 Pouces - Sac de Travail - Cuir à Tannage Végétal - 30 x 35 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Mira, grand sac cabas en cuir pour le travail et les loisirs.</strong> Le Mira passe sans effort du travail aux loisirs. Avec sa silhouette classique et ses dimensions pratiques de 30 x 35 cm, c'est le sac des femmes qui ont beaucoup à transporter sans renoncer au style. Ordinateur portable jusqu'à 15 pouces, documents A4, déjeuner, tenue de sport : tout y trouve sa place.</p><p>Des poches intérieures pour téléphone et portefeuille et une poche zippée pour les objets de valeur gardent tout organisé. Le sac se ferme par un aimant. Le fond renforcé permet au Mira de tenir droit et les poignées solides se portent confortablement, même lors d'une longue journée de travail. Cette version est réalisée en ${v.frMat}, coloris ${v.fr.toLowerCase()}.</p><h3>Caractéristiques du sac cabas Beocca Mira</h3><ul><li>Dimensions 30 x 35 cm</li><li>Grand compartiment principal avec place pour un ordinateur jusqu'à 15 pouces et des documents A4</li><li>Poches intérieures pour téléphone et portefeuille</li><li>Poche zippée pour les objets de valeur, fermeture magnétique</li><li>Fond renforcé et poignées solides</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>De la salle de réunion aux courses : le Mira est un grand sac cabas en cuir pour femme au design intemporel. Disponible en noir, marron foncé et daim noir.</p>`,
    },
  },

  'mason': {
    model: 'Mason',
    colours: { 'Cognac': { nl: 'Cognac', fr: 'Cognac' }, 'Bruin': { nl: 'Bruin', fr: 'Marron' } },
    nl: {
      title: v => `Beocca Mason Leren Laptoptas 15 inch Dames Heren - Aktetas met Gevoerd Laptopvak, Schouderband en Hengsels - Plantaardig Gelooid Leer - 40 x 32 x 15 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Mason, stijlvolle leren laptoptas voor professionals.</strong> De Mason is de leren laptoptas voor wie functionaliteit en elegantie wil combineren. Ontworpen om je laptop veilig te vervoeren zonder concessies aan stijl, is hij de metgezel voor je dagelijkse werk, van kantoor tot klantafspraak tot zakenreis.</p><p>Het speciaal gevoerde vak beschermt laptops tot 15 inch tegen stoten en krassen. Daarnaast is er ruime opbergruimte voor documenten en zijn er binnenvakken voor oplader, pennen en accessoires. Je draagt de tas aan de stevige hengsels of met de verstelbare schouderband. De YKK ritssluiting sluit alles veilig af. Afmetingen: 40 x 32 x 15 cm.</p><h3>Kenmerken van de Beocca Mason laptoptas</h3><ul><li>Gevoerd laptopvak voor laptops tot 15 inch</li><li>Afmetingen 40 x 32 x 15 cm</li><li>Ruime opbergruimte voor A4-documenten</li><li>Binnenvakken voor oplader, pennen en accessoires</li><li>Verstelbare schouderband en stevige hengsels</li><li>YKK ritssluiting</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Een leren laptoptas voor dames en heren die mooier wordt met de jaren in plaats van versleten. Verkrijgbaar in cognac en bruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Mason Sacoche Ordinateur Portable 15 Pouces en Cuir Femme Homme - Sac Business avec Compartiment Matelassé, Bandoulière et Poignées - Cuir à Tannage Végétal - 40 x 32 x 15 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Mason, élégante sacoche en cuir pour ordinateur portable.</strong> Le Mason est la sacoche en cuir de celles et ceux qui veulent allier fonctionnalité et élégance. Conçu pour transporter votre ordinateur en toute sécurité sans compromis sur le style, il vous accompagne au quotidien, du bureau au rendez-vous client et en voyage d'affaires.</p><p>Le compartiment matelassé protège les ordinateurs portables jusqu'à 15 pouces des chocs et des rayures. Vous disposez en plus d'un grand espace pour vos documents et de poches intérieures pour chargeur, stylos et accessoires. Vous portez le sac par ses poignées solides ou avec la bandoulière réglable. La fermeture éclair YKK ferme le tout en sécurité. Dimensions : 40 x 32 x 15 cm.</p><h3>Caractéristiques de la sacoche Beocca Mason</h3><ul><li>Compartiment matelassé pour ordinateur portable jusqu'à 15 pouces</li><li>Dimensions 40 x 32 x 15 cm</li><li>Grand espace pour documents A4</li><li>Poches intérieures pour chargeur, stylos et accessoires</li><li>Bandoulière réglable et poignées solides</li><li>Fermeture éclair YKK</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Une sacoche ordinateur en cuir pour femme et homme qui embellit avec les années au lieu de s'user. Disponible en cognac et marron. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'miles-toilettas': {
    model: 'Miles',
    colours: { 'Cognac': { nl: 'Cognac', fr: 'Cognac' }, 'Bruin': { nl: 'Bruin', fr: 'Marron' } },
    nl: {
      title: v => `Beocca Miles Leren Toilettas Heren Dames - Reis Toilettas met Waterbestendige Voering, YKK Rits en Ophanglus - Plantaardig Gelooid Leer - 3,5 liter - ${v.nl}`,
      desc: v => `<p><strong>Beocca Miles, luxueuze leren toilettas voor de moderne reiziger.</strong> De Miles combineert functionaliteit met tijdloze stijl. Of je nu dagelijks naar de sportschool gaat of een weekendje weg bent, deze toilettas houdt al je verzorgingsproducten netjes georganiseerd. Ruim maar compact: met 24 x 10 x 16 cm en 3,5 liter past alles wat je nodig hebt zonder veel ruimte in je bagage in te nemen.</p><p>Het ruime hoofdvak biedt plaats aan flessen en tubes, de binnenvakken houden kleinere items gescheiden. De waterbestendige voering beschermt tegen lekkages en is makkelijk schoon te maken. De stevige YKK rits haakt niet en met de ophanglus hang je de tas op in de badkamer of hotelkamer.</p><h3>Kenmerken van de Beocca Miles toilettas</h3><ul><li>Afmetingen 24 x 10 x 16 cm, inhoud 3,5 liter</li><li>Ruim hoofdvak voor flessen en tubes</li><li>Binnenvakken voor kleine items</li><li>Waterbestendige voering, makkelijk schoon te maken</li><li>Stevige YKK rits en ophanglus</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Een leren toilettas voor heren en dames die jaren aan goedkope plastic tasjes vervangt. Verkrijgbaar in cognac en bruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Miles Trousse de Toilette Homme Femme en Cuir - Trousse de Voyage avec Doublure Résistante à l'Eau, Glissière YKK et Boucle de Suspension - Cuir à Tannage Végétal - 3,5 litres - ${v.fr}`,
      desc: v => `<p><strong>Beocca Miles, trousse de toilette en cuir luxueuse pour le voyageur moderne.</strong> La Miles allie fonctionnalité et style intemporel. Salle de sport au quotidien ou escapade le week-end, cette trousse de toilette garde tous vos produits de soin bien organisés. Spacieuse mais compacte : avec ses 24 x 10 x 16 cm et ses 3,5 litres, tout ce dont vous avez besoin y trouve sa place sans encombrer vos bagages.</p><p>Le grand compartiment principal accueille flacons et tubes, les poches intérieures séparent les petits articles. La doublure résistante à l'eau protège des fuites et se nettoie facilement. La solide fermeture éclair YKK ne s'accroche pas et la boucle de suspension permet d'accrocher la trousse dans la salle de bain ou la chambre d'hôtel.</p><h3>Caractéristiques de la trousse de toilette Beocca Miles</h3><ul><li>Dimensions 24 x 10 x 16 cm, volume de 3,5 litres</li><li>Grand compartiment principal pour flacons et tubes</li><li>Poches intérieures pour les petits articles</li><li>Doublure résistante à l'eau, facile à nettoyer</li><li>Solide fermeture éclair YKK et boucle de suspension</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Une trousse de toilette en cuir pour homme et femme qui remplace des années de pochettes en plastique. Disponible en cognac et marron. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'seth': {
    model: 'Seth',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Beige': { nl: 'Beige', fr: 'Beige' }, 'Donkerbruin': { nl: 'Donkerbruin', fr: 'Marron foncé' } },
    nl: {
      title: v => `Beocca Seth Leren Pasjeshouder Dames Heren - Ultraslanke Kaarthouder voor 6 Pasjes - Creditcardhouder 10 x 10 x 1 cm - Plantaardig Gelooid Leer - ${v.nl}`,
      desc: v => `<p><strong>Beocca Seth, ultraslanke leren pasjeshouder voor minimalisten.</strong> De Seth is gemaakt voor wie houdt van eenvoud en functionaliteit. Met zijn ultraslanke ontwerp van 10 x 10 x 1 cm past hij moeiteloos in je broekzak, jas of tas, je merkt nauwelijks dat je hem bij je draagt.</p><p>In een tijd van contactloos betalen is een compacte pasjeshouder vaak alles wat je nodig hebt. De Seth biedt ruimte voor 6 pasjes, zoals je pinpas, creditcard, OV-chipkaart en rijbewijs, zonder de bulk van een traditionele portemonnee. De kaarten zijn makkelijk toegankelijk en zitten toch stevig op hun plek. Het plantaardig gelooide leer is stevig genoeg om zijn vorm te behouden, ook na maanden dagelijks gebruik in je broekzak.</p><h3>Kenmerken van de Beocca Seth pasjeshouder</h3><ul><li>Ultraslank formaat van 10 x 10 x 1 cm</li><li>Ruimte voor 6 pasjes</li><li>Lichtgewicht en compact</li><li>Minimalistisch design zonder overbodige vakjes of flappen</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Een slanke creditcardhouder voor dames en heren en een attent cadeau voor iedereen die kwaliteit en eenvoud waardeert. Verkrijgbaar in zwart, beige en donkerbruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Seth Porte-Cartes en Cuir Femme Homme - Porte-Cartes Ultra-Fin pour 6 Cartes - Étui Carte de Crédit 10 x 10 x 1 cm - Cuir à Tannage Végétal - ${v.fr}`,
      desc: v => `<p><strong>Beocca Seth, porte-cartes en cuir ultra-fin pour minimalistes.</strong> Le Seth est fait pour celles et ceux qui aiment la simplicité et la fonctionnalité. Avec son design ultra-fin de 10 x 10 x 1 cm, il se glisse sans effort dans une poche de pantalon, une veste ou un sac, vous remarquez à peine que vous le portez.</p><p>À l'heure du paiement sans contact, un porte-cartes compact suffit souvent. Le Seth offre de la place pour 6 cartes, comme votre carte bancaire, carte de crédit, carte de transport et permis, sans le volume d'un portefeuille traditionnel. Les cartes restent facilement accessibles tout en étant bien maintenues. Le cuir à tannage végétal est assez ferme pour garder sa forme, même après des mois d'usage quotidien dans une poche.</p><h3>Caractéristiques du porte-cartes Beocca Seth</h3><ul><li>Format ultra-fin de 10 x 10 x 1 cm</li><li>Place pour 6 cartes</li><li>Léger et compact</li><li>Design minimaliste sans compartiments ni rabats superflus</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Un porte-cartes fin pour femme et homme et un cadeau attentionné pour qui apprécie la qualité et la simplicité. Disponible en noir, beige et marron foncé. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'aris': {
    model: 'Aris',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Beige': { nl: 'Beige', fr: 'Beige' }, 'Bruin': { nl: 'Bruin', fr: 'Marron' } },
    nl: {
      title: v => `Beocca Aris Leren Portemonnee Dames Heren - Compacte Portefeuille met 8 Kaartsleuven en Muntvak met Rits - Plantaardig Gelooid Leer - 10 x 12 x 2 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Aris, tijdloze leren portemonnee met ruimte voor alles.</strong> De Aris combineert praktisch gemak met verfijnde elegantie. Met ruimte voor al je pasjes, contant geld en bonnetjes is het de portemonnee die je dagelijks met plezier pakt. Dankzij het slanke profiel van 10 x 12 x 2 cm past hij comfortabel in je tas of achterzak.</p><p>Meer dan 8 kaartsleuven houden je pasjes overzichtelijk, twee ruime vakken bieden plaats aan briefgeld en in het muntvak met rits zit je muntgeld veilig opgeborgen zonder gerinkel. Extra vakjes zijn er voor bonnetjes. De portemonnee sluit met een magneetsluiting. Het plantaardig gelooide leer wordt met gebruik soepeler en mooier.</p><h3>Kenmerken van de Beocca Aris portemonnee</h3><ul><li>Slank formaat van 10 x 12 x 2 cm</li><li>Meer dan 8 kaartsleuven voor pasjes</li><li>Twee ruime vakken voor briefgeld</li><li>Muntvak met rits</li><li>Extra vakjes voor bonnetjes, magneetsluiting</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Een leren portemonnee voor dames en heren die je jaren trouw blijft. Verkrijgbaar in zwart, beige en bruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Aris Portefeuille en Cuir Femme Homme - Portefeuille Compact avec 8 Emplacements Cartes et Porte-Monnaie Zippé - Cuir à Tannage Végétal - 10 x 12 x 2 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Aris, portefeuille en cuir intemporel avec de la place pour tout.</strong> L'Aris allie praticité et élégance raffinée. Avec de la place pour toutes vos cartes, vos espèces et vos reçus, c'est le portefeuille que vous prenez chaque jour avec plaisir. Grâce à son profil fin de 10 x 12 x 2 cm, il se glisse confortablement dans un sac ou une poche arrière.</p><p>Plus de 8 emplacements gardent vos cartes organisées, deux compartiments spacieux accueillent les billets et le porte-monnaie zippé range vos pièces en toute sécurité, sans bruit. Des poches supplémentaires sont prévues pour les reçus. Le portefeuille se ferme par un aimant. Le cuir à tannage végétal s'assouplit et embellit à l'usage.</p><h3>Caractéristiques du portefeuille Beocca Aris</h3><ul><li>Format fin de 10 x 12 x 2 cm</li><li>Plus de 8 emplacements pour cartes</li><li>Deux compartiments spacieux pour les billets</li><li>Porte-monnaie à fermeture éclair</li><li>Poches supplémentaires pour les reçus, fermeture magnétique</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>Un portefeuille en cuir pour femme et homme qui vous reste fidèle pendant des années. Disponible en noir, beige et marron. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },

  'leren-riem-oden': {
    model: 'Oden',
    colours: { 'Bruin': { nl: 'Bruin', fr: 'Marron' }, 'Cognac': { nl: 'Cognac', fr: 'Cognac' } },
    nl: {
      title: v => `Beocca Oden Leren Riem Heren - Broekriem met Klassieke Messing Gesp - Plantaardig Gelooid Leer - ${v.size} - ${v.nl}`,
      desc: v => `<p><strong>Beocca Oden, stoere leren herenriem van plantaardig gelooid leer.</strong> De Oden staat voor eenvoud, kracht en tijdloos vakmanschap. Gemaakt van dik, plantaardig gelooid leer dat met elk gebruik karaktervoller wordt en een prachtige patina ontwikkelt. Een goede riem is meer dan een functioneel accessoire: het is het detail dat je outfit afmaakt.</p><p>De klassieke messing gesp voegt een vleugje vintage charme toe en is gekozen om jarenlang intensief gebruik te doorstaan. De combinatie van het dikke leer en de stevige gesp maakt de Oden tot een riem die generaties meegaat. De riem is circa 3,5 cm breed en verkrijgbaar in de lengtes 95, 100 en 105 cm. Deze uitvoering: ${v.size}, ${v.nl.toLowerCase()}.</p><h3>Kenmerken van de Beocca Oden herenriem</h3><ul><li>Dik, 100% plantaardig gelooid leer</li><li>Klassieke messing gesp</li><li>Circa 3,5 cm breed</li><li>Verkrijgbaar in 95, 100 en 105 cm</li><li>Handgemaakt door ervaren ambachtslieden</li></ul>${NL_LEER}<p>Combineer de Oden met je favoriete jeans voor een casual look of draag hem bij een nette chino op kantoor. Een leren riem voor heren in bruin of cognac die past bij moderne én klassieke stijlen.</p>`,
    },
    fr: {
      title: v => `Beocca Oden Ceinture en Cuir Homme - Ceinture de Pantalon avec Boucle Classique en Laiton - Cuir à Tannage Végétal - ${v.size} - ${v.fr}`,
      desc: v => `<p><strong>Beocca Oden, ceinture homme robuste en cuir à tannage végétal.</strong> L'Oden incarne la simplicité, la force et l'artisanat intemporel. Fabriquée en cuir épais à tannage végétal, elle gagne en caractère à chaque port et développe une belle patine. Une bonne ceinture est plus qu'un accessoire fonctionnel : c'est le détail qui termine une tenue.</p><p>La boucle classique en laiton apporte une touche de charme vintage et a été choisie pour résister à des années d'usage intensif. L'association du cuir épais et de la boucle solide fait de l'Oden une ceinture qui traverse les générations. La ceinture mesure environ 3,5 cm de large et existe en 95, 100 et 105 cm. Cette version : ${v.size}, ${v.fr.toLowerCase()}.</p><h3>Caractéristiques de la ceinture Beocca Oden</h3><ul><li>Cuir épais, 100 % à tannage végétal</li><li>Boucle classique en laiton</li><li>Largeur d'environ 3,5 cm</li><li>Disponible en 95, 100 et 105 cm</li><li>Faite main par des artisans expérimentés</li></ul>${FR_CUIR}<p>Associez l'Oden à votre jean préféré pour un look décontracté ou portez-la avec un chino au bureau. Une ceinture en cuir pour homme, en marron ou cognac, qui convient aux styles modernes comme classiques.</p>`,
    },
  },

  'schoudertas-lua': {
    model: 'Lua',
    colours: { 'Zwart': { nl: 'Zwart', fr: 'Noir' }, 'Beige': { nl: 'Beige', fr: 'Beige' }, 'Donkerbruin': { nl: 'Donkerbruin', fr: 'Marron foncé' } },
    nl: {
      title: v => `Beocca Lua Leren Schoudertas Dames - Crossbody Tas met Twee Schouderbanden en 3 Vakken - Plantaardig Gelooid Leer - 27 x 20 x 10 cm - ${v.nl}`,
      desc: v => `<p><strong>Beocca Lua, elegante leren schoudertas voor elke gelegenheid.</strong> De Lua gaat moeiteloos mee van dagelijkse afspraken naar een avond uit. Haar elegante, eigentijdse design en de warme uitstraling van plantaardig gelooid leer maken haar een veelzijdige favoriet. De tas wordt geleverd met twee schouderbanden: een korte, deels gevlochten band en een lange, verstelbare band om haar als crossbody tas te dragen.</p><p>Het compacte formaat van 27 x 20 x 10 cm is precies berekend: groot genoeg voor je portemonnee, telefoon, sleutels en make-up, klein genoeg om nooit in de weg te zitten. De drie vakken met praktische binnenvakverdeling houden alles overzichtelijk. De tas sluit met een gesp, magneet en YKK ritssluitingen.</p><h3>Kenmerken van de Beocca Lua schoudertas</h3><ul><li>Afmetingen 27 x 20 x 10 cm</li><li>Twee schouderbanden: kort en deels gevlochten, lang en verstelbaar voor crossbody</li><li>3 vakken met praktische binnenvakverdeling</li><li>Sluiting met gesp, magneet en YKK ritssluitingen</li><li>100% plantaardig gelooid leer, handgemaakt</li></ul>${NL_LEER}<p>Van een zakelijke vergadering naar een lunch met vriendinnen tot een diner: de Lua is een leren schoudertas voor dames die bij elk moment van de dag past. Verkrijgbaar in zwart, beige en donkerbruin. Deze uitvoering: ${v.nl.toLowerCase()}.</p>`,
    },
    fr: {
      title: v => `Beocca Lua Sac Bandoulière Femme en Cuir - Sac Crossbody avec Deux Bandoulières et 3 Compartiments - Cuir à Tannage Végétal - 27 x 20 x 10 cm - ${v.fr}`,
      desc: v => `<p><strong>Beocca Lua, élégant sac bandoulière en cuir pour toutes les occasions.</strong> Le Lua passe sans effort des rendez-vous du quotidien à une soirée. Son design élégant et contemporain et la chaleur du cuir à tannage végétal en font un favori polyvalent. Le sac est livré avec deux bandoulières : une courte, partiellement tressée, et une longue, réglable, pour le porter en crossbody.</p><p>Son format compact de 27 x 20 x 10 cm est calculé au plus juste : assez grand pour votre portefeuille, téléphone, clés et maquillage, assez petit pour ne jamais gêner. Les trois compartiments et leur agencement intérieur pratique gardent tout organisé. Le sac se ferme par une boucle, un aimant et des fermetures éclair YKK.</p><h3>Caractéristiques du sac bandoulière Beocca Lua</h3><ul><li>Dimensions 27 x 20 x 10 cm</li><li>Deux bandoulières : courte et partiellement tressée, longue et réglable pour le crossbody</li><li>3 compartiments avec agencement intérieur pratique</li><li>Fermeture par boucle, aimant et glissières YKK</li><li>Cuir 100 % à tannage végétal, fait main</li></ul>${FR_CUIR}<p>D'une réunion professionnelle à un déjeuner entre amies et jusqu'au dîner : le Lua est un sac bandoulière en cuir pour femme qui convient à chaque moment de la journée. Disponible en noir, beige et marron foncé. Cette version : ${v.fr.toLowerCase()}.</p>`,
    },
  },
};
